/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.Koneksi;
import java.sql.Connection; // <-- Ganti baris ini
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bagusade_s
 */
public class form_kriteria extends javax.swing.JPanel {

    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_kriteria.class.getName());
    
    
    public form_kriteria() {
        initComponents();
        conn = config.Koneksi.getConnection();
        getData();
//        aktifButton();
//        nonAktifButton();
    }
        
    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tabel_kriteria.getModel();
        model.setRowCount(0);

        if (conn == null) {
            return; // Koneksi.getConnection() sudah menampilkan pesan error
        }

        String sql = "SELECT * FROM kriteria";

        try (PreparedStatement st = conn.prepareStatement(sql); ResultSet rs = st.executeQuery()) {

            while (rs.next()) {
                Object[] rowData = {
                    rs.getString("id"),
                    rs.getString("nama_kriteria"),
                    rs.getString("jenis_kriteria"),
                    rs.getString("bobot")
                };
                model.addRow(rowData);
            }

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error fetching kriteria data", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        dataKriteria = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_tambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kriteria = new javax.swing.JTable();
        tambahKaryawan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_namaKriteria = new javax.swing.JTextField();
        t_bobot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_kode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_jenisKriteria = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataKriteria.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 54, 129));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DATA KRITERIA");

        jSeparator2.setForeground(java.awt.Color.darkGray);

        btn_tambah.setBackground(new java.awt.Color(41, 54, 129));
        btn_tambah.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Cari:");

        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        tabel_kriteria.setBackground(new java.awt.Color(208, 231, 230));
        tabel_kriteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 204, 221)));
        tabel_kriteria.setForeground(new java.awt.Color(41, 54, 129));
        tabel_kriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Kriteria", "Jenis Kriteria", "Bobot"
            }
        ));
        tabel_kriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel_kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kriteriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kriteria);

        javax.swing.GroupLayout dataKriteriaLayout = new javax.swing.GroupLayout(dataKriteria);
        dataKriteria.setLayout(dataKriteriaLayout);
        dataKriteriaLayout.setHorizontalGroup(
            dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(dataKriteriaLayout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataKriteriaLayout.setVerticalGroup(
            dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataKriteria, "card2");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 54, 129));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH DATA KRITERIA");

        jSeparator1.setForeground(java.awt.Color.darkGray);

        btn_simpan.setBackground(new java.awt.Color(41, 54, 129));
        btn_simpan.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_batal.setBackground(new java.awt.Color(41, 54, 129));
        btn_batal.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("KEMBALI");
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Kriteria :");

        t_namaKriteria.setBackground(new java.awt.Color(255, 255, 255));
        t_namaKriteria.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_namaKriteria.setForeground(new java.awt.Color(0, 0, 0));
        t_namaKriteria.setCaretColor(new java.awt.Color(51, 51, 255));
        t_namaKriteria.addActionListener(this::t_namaKriteriaActionPerformed);

        t_bobot.setBackground(new java.awt.Color(255, 255, 255));
        t_bobot.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_bobot.setForeground(new java.awt.Color(0, 0, 0));
        t_bobot.setCaretColor(new java.awt.Color(51, 51, 255));
        t_bobot.addActionListener(this::t_bobotActionPerformed);

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bobot :");

        t_kode.setBackground(new java.awt.Color(255, 255, 255));
        t_kode.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_kode.setForeground(new java.awt.Color(0, 0, 0));
        t_kode.setCaretColor(new java.awt.Color(51, 51, 255));
        t_kode.addActionListener(this::t_kodeActionPerformed);

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Kriteria:");

        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jenis Kriteria :");

        combo_jenisKriteria.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        combo_jenisKriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Kriteria --", "Benefit", "Cost" }));
        combo_jenisKriteria.setBorder(null);
        combo_jenisKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_update.setBackground(new java.awt.Color(41, 54, 129));
        btn_update.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(this::btn_updateActionPerformed);

        btn_hapus.setBackground(new java.awt.Color(41, 54, 129));
        btn_hapus.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaKriteria)
                    .addComponent(t_kode)
                    .addComponent(combo_jenisKriteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_bobot)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_jenisKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_bobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahKaryawanLayout = new javax.swing.GroupLayout(tambahKaryawan);
        tambahKaryawan.setLayout(tambahKaryawanLayout);
        tambahKaryawanLayout.setHorizontalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahKaryawanLayout.setVerticalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(tambahKaryawan, "card2");

        jPanel1.add(mainPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahKaryawan);
        mainPanel.repaint();
        mainPanel.revalidate();

        nonAktifButton();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void tabel_kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kriteriaMouseClicked
        int selectedRow = tabel_kriteria.getSelectedRow();
        if(selectedRow != -1) {
            String kode     = tabel_kriteria.getValueAt(selectedRow, 0).toString();
            String nama     = tabel_kriteria.getValueAt(selectedRow, 1).toString();
            String jk       = tabel_kriteria.getValueAt(selectedRow, 2).toString();
            String bobot    = tabel_kriteria.getValueAt(selectedRow, 3).toString();

            t_kode.setText(kode);
            t_namaKriteria.setText(nama);
            combo_jenisKriteria.setSelectedItem(jk);
            t_bobot.setText(bobot);

            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahKaryawan);
            mainPanel.repaint();
            mainPanel.revalidate();
        }

        btn_simpan.setEnabled(false);
        btn_update.setEnabled(true);
        btn_hapus.setEnabled(true);
    }//GEN-LAST:event_tabel_kriteriaMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String kode = t_kode.getText();
        String nama = t_namaKriteria.getText();
        String jk = (String) combo_jenisKriteria.getSelectedItem();
        String bobot = t_bobot.getText();

        if(kode.isEmpty() || nama.isEmpty() || jk == null || jk.startsWith("--") || bobot.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Double.parseDouble(bobot);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bobot harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "INSERT INTO kriteria (id, nama_kriteria, jenis_kriteria, bobot) VALUES (?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, kode);
            st.setString(2, nama);
            st.setString(3, jk);
            st.setString(4, bobot);

            int rowInserted = st.executeUpdate();
            if (rowInserted > 0){
                JOptionPane.showMessageDialog(this, "Data berhasil di input!");
                resetForm();
                getData();
            }
            st.close();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error inserting kriteria data", e);
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data. Periksa apakah id kriteria sudah dipakai.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataKriteria);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void t_bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bobotActionPerformed

    private void t_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int selectedRow = tabel_kriteria.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di perbarui!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String kode = t_kode.getText().trim();
        String nama = t_namaKriteria.getText().trim();
        String jk = (String) combo_jenisKriteria.getSelectedItem();
        String bobot = t_bobot.getText().trim();
        

        if (kode.isEmpty() || nama.isEmpty() || jk == null || jk.startsWith("--") || bobot.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "UPDATE kriteria SET nama_kriteria=?, jenis_kriteria=?, bobot=? WHERE id=?";
        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, nama);
            st.setString(2, jk);
            st.setDouble(3, Double.parseDouble(bobot));   // bobot = double, bukan String
            st.setString(4, kode);                        // kode = id (varchar), dipakai di WHERE

            int rowUpdated = st.executeUpdate();
            if (rowUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil di perbarui!");
                resetForm();
                nonAktifButton();
                aktifButton();
                getData();
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau tidak ada perubahan.", "Info", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error updating karyawan data", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataKriteria);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int selectedRow = tabel_kriteria.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di hapus!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String id = tabel_kriteria.getValueAt(selectedRow, 0).toString();
            
            try {
                String sql = "DELETE FROM kriteria WHERE id=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, id);
                
                int rowDelete = st.executeUpdate();
                if (rowDelete > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    resetForm();
                    getData();
                    aktifButton();
                    nonAktifButton();
                }
                
                st.close();
            } catch(Exception e) {
                logger.log(Level.SEVERE, "Error fetching karyawan data", e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void t_namaKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaKriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaKriteriaActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        DefaultTableModel model = (DefaultTableModel) tabel_kriteria.getModel();
        model.setRowCount(0);
        
        String cari = t_cari.getText();
        
        try {
            String sql = "SELECT * FROM kriteria WHERE id LIKE ? OR nama_kriteria LIKE ? OR jenis_kriteria LIKE ? OR bobot LIKE ?";
            PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, "%" + cari + "%");
                st.setString(2, "%" + cari + "%");
                st.setString(3, "%" + cari + "%");
                st.setString(4, "%" + cari + "%");
            
            ResultSet rs = st.executeQuery();
            
            while(rs.next()) {
                String id      = rs.getString("id");
                String nama      = rs.getString("nama_kriteria");
                String jk      = rs.getString("jenis_kriteria");
                String bobot      = rs.getString("bobot");
                
                Object[] rowData = {id,nama,jk,bobot};
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error fetching kriteria data", e);
        }
    }//GEN-LAST:event_t_cariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_jenisKriteria;
    private javax.swing.JPanel dataKriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_bobot;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_kode;
    private javax.swing.JTextField t_namaKriteria;
    private javax.swing.JTable tabel_kriteria;
    private javax.swing.JPanel tambahKaryawan;
    // End of variables declaration//GEN-END:variables
    
    private void resetForm() {
        t_kode.setText("");
        t_namaKriteria.setText("");
        combo_jenisKriteria.setSelectedIndex(0);
        t_bobot.setText("");
    }
    
    private void nonAktifButton() {
        btn_simpan.setEnabled(true);
        btn_update.setEnabled(false);
        btn_hapus.setEnabled(false);
    }

    private void aktifButton() {
        btn_tambah.setEnabled(true);
        btn_batal.setEnabled(true);
    }


}
