/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.Koneksi;
import java.sql.Connection; // <-- Ganti baris ini
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bagusade_s
 */
public class form_karyawan extends javax.swing.JPanel {

    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_karyawan.class.getName());
    
    
    public form_karyawan() {
        initComponents();
        conn = config.Koneksi.getConnection();
        getData();
        aktifButton();
        nonAktifButton();
    }
        
    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tabel_karyawan.getModel();
        model.setRowCount(0);

        if (conn == null) {
            return; // Koneksi.getConnection() sudah menampilkan pesan error
        }

        String sql = "SELECT * FROM karyawan";

        try (PreparedStatement st = conn.prepareStatement(sql); ResultSet rs = st.executeQuery()) {

            while (rs.next()) {
                Object[] rowData = {
                    rs.getString("kode_karyawan"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                };
                model.addRow(rowData);
            }

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error fetching karyawan data", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataKaryawan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_karyawan = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tambahKaryawan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_namaKaryawan = new javax.swing.JTextField();
        t_noHP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_kode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_jenisKelamin = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_alamat = new javax.swing.JTextArea();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(java.awt.Color.darkGray);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 54, 129));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DATA KARYAWAN");

        jSeparator2.setForeground(java.awt.Color.darkGray);

        btn_tambah.setBackground(new java.awt.Color(41, 54, 129));
        btn_tambah.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        tabel_karyawan.setBackground(new java.awt.Color(208, 231, 230));
        tabel_karyawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 204, 221)));
        tabel_karyawan.setForeground(new java.awt.Color(41, 54, 129));
        tabel_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "Telepon", "Alamat"
            }
        ));
        tabel_karyawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_karyawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_karyawan);

        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Cari:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dataKaryawanLayout = new javax.swing.GroupLayout(dataKaryawan);
        dataKaryawan.setLayout(dataKaryawanLayout);
        dataKaryawanLayout.setHorizontalGroup(
            dataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataKaryawanLayout.setVerticalGroup(
            dataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(dataKaryawan, "card2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 54, 129));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH DATA KARYAWAN");

        jSeparator1.setForeground(java.awt.Color.darkGray);

        btn_simpan.setBackground(new java.awt.Color(41, 54, 129));
        btn_simpan.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_batal.setBackground(new java.awt.Color(41, 54, 129));
        btn_batal.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("KEMBALI");
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Karyawan :");

        t_namaKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        t_namaKaryawan.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_namaKaryawan.setForeground(new java.awt.Color(0, 0, 0));
        t_namaKaryawan.setCaretColor(new java.awt.Color(51, 51, 255));
        t_namaKaryawan.addActionListener(this::t_namaKaryawanActionPerformed);

        t_noHP.setBackground(new java.awt.Color(255, 255, 255));
        t_noHP.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_noHP.setForeground(new java.awt.Color(0, 0, 0));
        t_noHP.setCaretColor(new java.awt.Color(51, 51, 255));
        t_noHP.addActionListener(this::t_noHPActionPerformed);

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("No. Handphone :");

        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Alamat :");

        t_kode.setBackground(new java.awt.Color(255, 255, 255));
        t_kode.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_kode.setForeground(new java.awt.Color(0, 0, 0));
        t_kode.setCaretColor(new java.awt.Color(51, 51, 255));
        t_kode.addActionListener(this::t_kodeActionPerformed);

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Karyawan :");

        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jenis Kelamin :");

        combo_jenisKelamin.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        combo_jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Kelamin --", "Laki-laki", "Perempuan" }));
        combo_jenisKelamin.setBorder(null);
        combo_jenisKelamin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_update.setBackground(new java.awt.Color(41, 54, 129));
        btn_update.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(this::btn_updateActionPerformed);

        btn_hapus.setBackground(new java.awt.Color(41, 54, 129));
        btn_hapus.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        t_alamat.setColumns(20);
        t_alamat.setRows(5);
        jScrollPane2.setViewportView(t_alamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaKaryawan)
                    .addComponent(t_kode)
                    .addComponent(combo_jenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_noHP)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tambahKaryawanLayout = new javax.swing.GroupLayout(tambahKaryawan);
        tambahKaryawan.setLayout(tambahKaryawanLayout);
        tambahKaryawanLayout.setHorizontalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahKaryawanLayout.setVerticalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(tambahKaryawan, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String kode = t_kode.getText();
        String nama = t_namaKaryawan.getText();
        String jk = (String) combo_jenisKelamin.getSelectedItem();
        String telepon = t_noHP.getText();
        String alamat = t_alamat.getText();
        
        if(kode.isEmpty() || nama.isEmpty() || jk == null || jk.startsWith("--") || telepon.isEmpty() || alamat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "INSERT INTO karyawan (kode_karyawan, nama, jenis_kelamin, no_hp, alamat) VALUES (?,?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, kode);
            st.setString(2, nama);
            st.setString(3, jk);
            st.setString(4, telepon);
            st.setString(5, alamat);
            
            int rowInserted = st.executeUpdate();
            if (rowInserted > 0){
                JOptionPane.showMessageDialog(this, "Data berhasil di input!");
                resetForm();
                getData();
            }
            st.close();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error inserting karyawan data", e);
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data. Periksa apakah kode karyawan sudah dipakai.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void t_namaKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaKaryawanActionPerformed

    private void t_noHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_noHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noHPActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int selectedRow = tabel_karyawan.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di hapus!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String id = tabel_karyawan.getValueAt(selectedRow, 0).toString();
            
            try {
                String sql = "DELETE FROM karyawan WHERE kode_karyawan=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, id);
                
                int rowDelete = st.executeUpdate();
                if (rowDelete > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    resetForm();
                    getData();
                    aktifButton();
                    nonAktifButton();
                }
                
                st.close();
            } catch(Exception e) {
                logger.log(Level.SEVERE, "Error fetching karyawan data", e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int selectedRow = tabel_karyawan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di perbarui!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String kode = t_kode.getText().trim();
        String nama = t_namaKaryawan.getText().trim();
        String jk = (String) combo_jenisKelamin.getSelectedItem();
        String telepon = t_noHP.getText().trim();
        String alamat = t_alamat.getText().trim();

        if (kode.isEmpty() || nama.isEmpty() || jk == null || jk.startsWith("--") || telepon.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "UPDATE karyawan SET nama=?, jenis_kelamin=?, no_hp=?, alamat=? WHERE kode_karyawan=?";
        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, nama);
            st.setString(2, jk);
            st.setString(3, telepon);
            st.setString(4, alamat);
            st.setString(5, kode);

            int rowUpdated = st.executeUpdate();
            if (rowUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil di perbarui!");
                resetForm();
                nonAktifButton();
                aktifButton();
                getData();
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau tidak ada perubahan.", "Info", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error updating karyawan data", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(dataKaryawan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahKaryawan);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        nonAktifButton();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(dataKaryawan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void t_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeActionPerformed

    private void tabel_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_karyawanMouseClicked
        int selectedRow = tabel_karyawan.getSelectedRow();
        if(selectedRow != -1) {
            String kode     = tabel_karyawan.getValueAt(selectedRow, 0).toString();
            String nama     = tabel_karyawan.getValueAt(selectedRow, 1).toString();
            String jk       = tabel_karyawan.getValueAt(selectedRow, 2).toString();
            String telepon  = tabel_karyawan.getValueAt(selectedRow, 3).toString();
            String alamat   = tabel_karyawan.getValueAt(selectedRow, 4).toString();
            
            t_kode.setText(kode);
            t_namaKaryawan.setText(nama);
            combo_jenisKelamin.setSelectedItem(jk);
            t_noHP.setText(telepon);
            t_alamat.setText(alamat);
        
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahKaryawan);
            mainPanel.repaint();
            mainPanel.revalidate();
        }
        
        btn_simpan.setEnabled(false);
        btn_update.setEnabled(true);
        btn_hapus.setEnabled(true);
    }//GEN-LAST:event_tabel_karyawanMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        DefaultTableModel model = (DefaultTableModel) tabel_karyawan.getModel();
        model.setRowCount(0);
        
        String cari = t_cari.getText();
        
        try {
            String sql = "SELECT * FROM karyawan WHERE kode_karyawan LIKE ? OR nama LIKE ? OR no_hp LIKE ? OR alamat LIKE ?";
            PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, "%" + cari + "%");
                st.setString(2, "%" + cari + "%");
                st.setString(3, "%" + cari + "%");
                st.setString(4, "%" + cari + "%");
            
            ResultSet rs = st.executeQuery();
            
            while(rs.next()) {
                Object[] rowData = {
                    rs.getString("kode_karyawan"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                };
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error fetching karyawan data", e);
        }
    }//GEN-LAST:event_t_cariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_jenisKelamin;
    private javax.swing.JPanel dataKaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea t_alamat;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_kode;
    private javax.swing.JTextField t_namaKaryawan;
    private javax.swing.JTextField t_noHP;
    private javax.swing.JTable tabel_karyawan;
    private javax.swing.JPanel tambahKaryawan;
    // End of variables declaration//GEN-END:variables
    private void resetForm() {
        t_kode.setText("");
        t_namaKaryawan.setText("");
        combo_jenisKelamin.setSelectedIndex(0);
        t_noHP.setText("");
        t_alamat.setText("");
    }
    
    private void nonAktifButton() {
        btn_simpan.setEnabled(true);
        btn_update.setEnabled(false);
        btn_hapus.setEnabled(false);
    }

    private void aktifButton() {
        btn_tambah.setEnabled(true);
        btn_batal.setEnabled(true);
    }

}
