/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.Koneksi;
import java.sql.Connection; // <-- Ganti baris ini
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JTextField;
/**
 *
 * @author bagusade_s
 */
public class form_penilaian extends javax.swing.JPanel {

    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_penilaian.class.getName());
    private int selectedId; // menyimpan id baris penilaian yang sedang dipilih untuk update
    
    public form_penilaian() {
       initComponents();
        conn = config.Koneksi.getConnection();
        t_namaKaryawan.setEditable(false); // poin di bawah
        loadComboKaryawan();
        setupComboListener();
        getData();
        aktifButton();
        nonAktifButton();
    }

    private void loadComboKaryawan() {
        combo_kodeKaryawan.removeAllItems();
        String sql = "SELECT kode_karyawan FROM karyawan";
        try (PreparedStatement st = conn.prepareStatement(sql); ResultSet rs = st.executeQuery()) {
            while (rs.next()) {
                combo_kodeKaryawan.addItem(rs.getString("kode_karyawan"));
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error loading kode karyawan combo", e);
        }
    }

    private void setupComboListener() {
        combo_kodeKaryawan.addActionListener(evt -> {
            String kode = (String) combo_kodeKaryawan.getSelectedItem();
            if (kode == null) return;
            String sql = "SELECT nama FROM karyawan WHERE kode_karyawan = ?";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, kode);
                try (ResultSet rs = st.executeQuery()) {
                    if (rs.next()) {
                        t_namaKaryawan.setText(rs.getString("nama"));
                    }
                }
            } catch (Exception e) {
                logger.log(Level.SEVERE, "Error fetching nama karyawan", e);
            }
        });
    }
        
    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tabel_penilaian.getModel();
        model.setRowCount(0);
        if (conn == null) {
            return; // Koneksi.getConnection() sudah menampilkan pesan error
        }
        String sql = "SELECT p.id, p.kode_karyawan, k.nama, "
                   + "p.c1, p.c2, p.c3, p.c4, p.c5, p.c6, p.c7, p.c8, p.c9, p.c10 "
                   + "FROM penilaian p "
                   + "JOIN karyawan k ON p.kode_karyawan = k.kode_karyawan";
        try (PreparedStatement st = conn.prepareStatement(sql); ResultSet rs = st.executeQuery()) {
            while (rs.next()) {
                Object[] rowData = {
                    rs.getInt("id"),
                    rs.getString("kode_karyawan"),
                    rs.getString("nama"),
                    rs.getDouble("c1"),
                    rs.getDouble("c2"),
                    rs.getDouble("c3"),
                    rs.getDouble("c4"),
                    rs.getDouble("c5"),
                    rs.getDouble("c6"),
                    rs.getDouble("c7"),
                    rs.getDouble("c8"),
                    rs.getDouble("c9"),
                    rs.getDouble("c10")
                };
                model.addRow(rowData);
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error fetching penilaian data", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        dataPenilaian = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penilaian = new javax.swing.JTable();
        tambahPenilaian = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_namaKaryawan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_kodeKaryawan = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        t_c1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_c2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_c3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_c4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t_c5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_c10 = new javax.swing.JTextField();
        t_c9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t_c8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t_c7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t_c6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataPenilaian.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 54, 129));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PENILAIAN");

        jSeparator2.setForeground(java.awt.Color.darkGray);

        btn_tambah.setBackground(new java.awt.Color(41, 54, 129));
        btn_tambah.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        tabel_penilaian.setBackground(new java.awt.Color(208, 231, 230));
        tabel_penilaian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 204, 221)));
        tabel_penilaian.setForeground(new java.awt.Color(41, 54, 129));
        tabel_penilaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kode Karyawan", "Nama Karyawan", "Kedisiplinan", "Kualitas kerja", "Kecepatan kerja", "Sikap kpd pelanggan", "Tanggung jawab", "Kerja sama", "S.O.P", "Kehadiran", "Jujur", "Efisiensi bahan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_penilaian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel_penilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penilaianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_penilaian);

        javax.swing.GroupLayout dataPenilaianLayout = new javax.swing.GroupLayout(dataPenilaian);
        dataPenilaian.setLayout(dataPenilaianLayout);
        dataPenilaianLayout.setHorizontalGroup(
            dataPenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenilaianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(dataPenilaianLayout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        dataPenilaianLayout.setVerticalGroup(
            dataPenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenilaianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataPenilaian, "card2");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 54, 129));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH PENILAIAN");

        jSeparator1.setForeground(java.awt.Color.darkGray);

        btn_simpan.setBackground(new java.awt.Color(41, 54, 129));
        btn_simpan.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_batal.setBackground(new java.awt.Color(41, 54, 129));
        btn_batal.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("KEMBALI");
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Karyawan :");

        t_namaKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        t_namaKaryawan.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_namaKaryawan.setForeground(new java.awt.Color(0, 0, 0));
        t_namaKaryawan.setCaretColor(new java.awt.Color(51, 51, 255));
        t_namaKaryawan.addActionListener(this::t_namaKaryawanActionPerformed);

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Karyawan :");

        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("C1");

        combo_kodeKaryawan.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        combo_kodeKaryawan.setBorder(null);
        combo_kodeKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_update.setBackground(new java.awt.Color(41, 54, 129));
        btn_update.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(this::btn_updateActionPerformed);

        btn_hapus.setBackground(new java.awt.Color(41, 54, 129));
        btn_hapus.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        t_c1.setBackground(new java.awt.Color(255, 255, 255));
        t_c1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c1.setForeground(new java.awt.Color(0, 0, 0));
        t_c1.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c1.addActionListener(this::t_c1ActionPerformed);

        jLabel9.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("C2");

        t_c2.setBackground(new java.awt.Color(255, 255, 255));
        t_c2.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c2.setForeground(new java.awt.Color(0, 0, 0));
        t_c2.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c2.addActionListener(this::t_c2ActionPerformed);

        jLabel10.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("C3");

        t_c3.setBackground(new java.awt.Color(255, 255, 255));
        t_c3.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c3.setForeground(new java.awt.Color(0, 0, 0));
        t_c3.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c3.addActionListener(this::t_c3ActionPerformed);

        jLabel11.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("C4");

        t_c4.setBackground(new java.awt.Color(255, 255, 255));
        t_c4.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c4.setForeground(new java.awt.Color(0, 0, 0));
        t_c4.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c4.addActionListener(this::t_c4ActionPerformed);

        jLabel12.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("C5");

        t_c5.setBackground(new java.awt.Color(255, 255, 255));
        t_c5.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c5.setForeground(new java.awt.Color(0, 0, 0));
        t_c5.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c5.addActionListener(this::t_c5ActionPerformed);

        jLabel13.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("C10");

        t_c10.setBackground(new java.awt.Color(255, 255, 255));
        t_c10.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c10.setForeground(new java.awt.Color(0, 0, 0));
        t_c10.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c10.addActionListener(this::t_c10ActionPerformed);

        t_c9.setBackground(new java.awt.Color(255, 255, 255));
        t_c9.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c9.setForeground(new java.awt.Color(0, 0, 0));
        t_c9.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c9.addActionListener(this::t_c9ActionPerformed);

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("C9");

        t_c8.setBackground(new java.awt.Color(255, 255, 255));
        t_c8.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c8.setForeground(new java.awt.Color(0, 0, 0));
        t_c8.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c8.addActionListener(this::t_c8ActionPerformed);

        jLabel15.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("C8");

        t_c7.setBackground(new java.awt.Color(255, 255, 255));
        t_c7.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c7.setForeground(new java.awt.Color(0, 0, 0));
        t_c7.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c7.addActionListener(this::t_c7ActionPerformed);

        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("C7");

        t_c6.setBackground(new java.awt.Color(255, 255, 255));
        t_c6.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_c6.setForeground(new java.awt.Color(0, 0, 0));
        t_c6.setCaretColor(new java.awt.Color(51, 51, 255));
        t_c6.addActionListener(this::t_c6ActionPerformed);

        jLabel17.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("C6");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("== Catatan ==\n\nC1 = Kedisiplinan, C2 = Kualitas Pengerjaan, C3 = Kecepatan Kerja, C4 = Sikap Trhdp Pelanggan, C5 = Tanggung Jawab Trhdp Alat,\nC6 = Kerja Sama, C7 = Ketaatan Pada SOP, C8 = Kehadiran, C9 = Kejujuran, C10 = Efisiensi Bahan");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(t_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(t_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(t_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(t_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(t_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(t_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(t_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(t_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(t_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(t_c10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                                .addComponent(btn_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hapus))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_kodeKaryawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_namaKaryawan)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_kodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_c10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahPenilaianLayout = new javax.swing.GroupLayout(tambahPenilaian);
        tambahPenilaian.setLayout(tambahPenilaianLayout);
        tambahPenilaianLayout.setHorizontalGroup(
            tambahPenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahPenilaianLayout.setVerticalGroup(
            tambahPenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(tambahPenilaian, "card2");

        jPanel1.add(mainPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int selectedRow = tabel_penilaian.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM penilaian WHERE id=?";
        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, selectedId);
            int rowDeleted = st.executeUpdate();
            if (rowDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                resetForm();
                nonAktifButton();
                getData();
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error deleting penilaian data", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
         int selectedRow = tabel_penilaian.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin di perbarui!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JTextField[] fields = {
                t_c1, t_c2, t_c3, t_c4, t_c5, t_c6, t_c7, t_c8, t_c9, t_c10
            };
            double[] nilai = new double[10];

            for (int i = 0; i < fields.length; i++) {
                String val = fields[i].getText().trim();
                if (val.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Semua kolom C1-C10 harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                try {
                    nilai[i] = Double.parseDouble(val);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Nilai C" + (i + 1) + " harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            String sql = "UPDATE penilaian SET c1=?, c2=?, c3=?, c4=?, c5=?, c6=?, c7=?, c8=?, c9=?, c10=? WHERE id=?";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                for (int i = 0; i < nilai.length; i++) {
                    st.setDouble(i + 1, nilai[i]);
                }
                st.setInt(11, selectedId);
                int rowUpdated = st.executeUpdate();
                if (rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Data penilaian berhasil diperbarui!");
                    resetForm();
                    nonAktifButton();
                    aktifButton();
                    getData();
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau tidak ada perubahan.", "Info", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                logger.log(Level.SEVERE, "Error updating penilaian data", e);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataPenilaian);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void t_namaKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaKaryawanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataPenilaian);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String kode = (String) combo_kodeKaryawan.getSelectedItem();
        if (kode == null || kode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih kode karyawan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ambil & validasi c1-c10
        double[] nilai = new double[10];
        JTextField[] fields = {
            t_c1, t_c2, t_c3, t_c4, t_c5, t_c6, t_c7, t_c8, t_c9, t_c10
        };

        for (int i = 0; i < fields.length; i++) {
            String val = fields[i].getText().trim();
            if (val.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua kolom C1-C10 harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                nilai[i] = Double.parseDouble(val);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nilai C" + (i + 1) + " harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String sql = "INSERT INTO penilaian (kode_karyawan, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10) "
        + "VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, kode);
            for (int i = 0; i < nilai.length; i++) {
                st.setDouble(i + 2, nilai[i]);
            }
            int rowInserted = st.executeUpdate();
            if (rowInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data penilaian berhasil disimpan!");
                resetForm();
                getData();
            }
        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Kode karyawan tidak ditemukan di data karyawan!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error inserting penilaian data", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void t_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c1ActionPerformed

    private void t_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c2ActionPerformed

    private void t_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c3ActionPerformed

    private void t_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c4ActionPerformed

    private void t_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c5ActionPerformed

    private void t_c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c10ActionPerformed

    private void t_c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c9ActionPerformed

    private void t_c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c8ActionPerformed

    private void t_c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c7ActionPerformed

    private void t_c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c6ActionPerformed

    private void tabel_penilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penilaianMouseClicked
        int selectedRow = tabel_penilaian.getSelectedRow();
        if (selectedRow != -1) {
            selectedId = Integer.parseInt(tabel_penilaian.getValueAt(selectedRow, 0).toString());
            String kode = tabel_penilaian.getValueAt(selectedRow, 1).toString();
            String nama = tabel_penilaian.getValueAt(selectedRow, 2).toString();

            combo_kodeKaryawan.setSelectedItem(kode);
            combo_kodeKaryawan.setEnabled(false); // kunci saat mode update
            t_namaKaryawan.setText(nama);

            t_c1.setText(tabel_penilaian.getValueAt(selectedRow, 3).toString());
            t_c2.setText(tabel_penilaian.getValueAt(selectedRow, 4).toString());
            t_c3.setText(tabel_penilaian.getValueAt(selectedRow, 5).toString());
            t_c4.setText(tabel_penilaian.getValueAt(selectedRow, 6).toString());
            t_c5.setText(tabel_penilaian.getValueAt(selectedRow, 7).toString());
            t_c6.setText(tabel_penilaian.getValueAt(selectedRow, 8).toString());
            t_c7.setText(tabel_penilaian.getValueAt(selectedRow, 9).toString());
            t_c8.setText(tabel_penilaian.getValueAt(selectedRow, 10).toString());
            t_c9.setText(tabel_penilaian.getValueAt(selectedRow, 11).toString());
            t_c10.setText(tabel_penilaian.getValueAt(selectedRow, 12).toString());

            mainPanel.removeAll();
            mainPanel.add(tambahPenilaian);
            mainPanel.revalidate();
            mainPanel.repaint();
        }
        btn_simpan.setEnabled(false);
        btn_update.setEnabled(true);
        btn_hapus.setEnabled(true);
    }//GEN-LAST:event_tabel_penilaianMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahPenilaian);
        mainPanel.repaint();
        mainPanel.revalidate();

        nonAktifButton();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked

    }//GEN-LAST:event_btn_tambahMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_kodeKaryawan;
    private javax.swing.JPanel dataPenilaian;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_c1;
    private javax.swing.JTextField t_c10;
    private javax.swing.JTextField t_c2;
    private javax.swing.JTextField t_c3;
    private javax.swing.JTextField t_c4;
    private javax.swing.JTextField t_c5;
    private javax.swing.JTextField t_c6;
    private javax.swing.JTextField t_c7;
    private javax.swing.JTextField t_c8;
    private javax.swing.JTextField t_c9;
    private javax.swing.JTextField t_namaKaryawan;
    private javax.swing.JTable tabel_penilaian;
    private javax.swing.JPanel tambahPenilaian;
    // End of variables declaration//GEN-END:variables
    
    private void resetForm() {
        combo_kodeKaryawan.setSelectedIndex(-1);
        t_namaKaryawan.setText("");
        t_c1.setText("");
        t_c2.setText("");
        t_c3.setText("");
        t_c4.setText("");
        t_c5.setText("");
        t_c6.setText("");
        t_c7.setText("");
        t_c8.setText("");
        t_c9.setText("");
        t_c10.setText("");
        combo_kodeKaryawan.setEnabled(true);
        selectedId = 0;
    }

    private void nonAktifButton() {
        btn_update.setEnabled(false);
        btn_hapus.setEnabled(false);
    }

    private void aktifButton() {
        btn_tambah.setEnabled(true);
        btn_batal.setEnabled(true);
    }
}

