/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.Koneksi;
import java.sql.Connection; // <-- Ganti baris ini
import java.sql.PreparedStatement; 
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.util.Map;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author bagusade_s
 */
public class form_kriteria1 extends javax.swing.JPanel {

    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_kriteria1.class.getName());
    
    
    public form_kriteria1() {
        initComponents();
        conn = config.Koneksi.getConnection();
//        getData();
//        aktifButton();
//        nonAktifButton();
    }
        
//    private void getData() {
//        DefaultTableModel model = (DefaultTableModel) tabel_kriteria.getModel();
//        model.setRowCount(0);
//
//        if (conn == null) {
//            throw new IllegalStateException("Database connection is null");
//        }
//
//        String sql = "SELECT * FROM kriteria";
//
//        try (PreparedStatement st = conn.prepareStatement(sql); ResultSet rs = st.executeQuery()) {
//
//            while (rs.next()) {
//                Object[] rowData = {
//                    rs.getString("id"),
//                    rs.getString("nama_kriteria"),
//                    rs.getString("jenis_kriteria"),
//                    rs.getString("bobot")
//                };
//                model.addRow(rowData);
//            }
//
//        } catch (Exception e) {
//            logger.log(Level.SEVERE, "Error fetching kriteria data", e);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        report = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        ctk_kriteria = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ctk_penilaian = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ctk_karyawan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ctk_ranking = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tambahKaryawan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_namaKriteria = new javax.swing.JTextField();
        t_bobot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_kode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_jenisKriteria = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        report.setBackground(new java.awt.Color(255, 255, 255));
        report.setForeground(java.awt.Color.darkGray);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(41, 54, 129));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Laporan");

        jSeparator3.setForeground(java.awt.Color.darkGray);

        jPanel4.setBackground(new java.awt.Color(41, 54, 129));

        ctk_kriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-category-100.png"))); // NOI18N
        ctk_kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctk_kriteriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(41, 54, 129));

        ctk_penilaian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-numbers-100.png"))); // NOI18N
        ctk_penilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctk_penilaianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_penilaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_penilaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(41, 54, 129));

        ctk_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-users-100.png"))); // NOI18N
        ctk_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctk_karyawanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ctk_karyawan)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Laporan");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Laporan");

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Laporan");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-users-100.png"))); // NOI18N

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data Karyawan");

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Data Kriteria");

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Data Penilaian");

        jPanel7.setBackground(new java.awt.Color(41, 54, 129));

        ctk_ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-rank-100.png"))); // NOI18N
        ctk_ranking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctk_rankingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_ranking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctk_ranking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Laporan");

        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Hasil Peringkat");

        javax.swing.GroupLayout reportLayout = new javax.swing.GroupLayout(report);
        report.setLayout(reportLayout);
        reportLayout.setHorizontalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(reportLayout.createSequentialGroup()
                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(reportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3))))
                .addContainerGap())
        );
        reportLayout.setVerticalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportLayout.createSequentialGroup()
                        .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(reportLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)))))
                    .addGroup(reportLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reportLayout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel19))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        mainPanel.add(report, "card3");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 54, 129));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH DATA KRITERIA");

        jSeparator1.setForeground(java.awt.Color.darkGray);

        btn_simpan.setBackground(new java.awt.Color(41, 54, 129));
        btn_simpan.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_batal.setBackground(new java.awt.Color(41, 54, 129));
        btn_batal.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("KEMBALI");
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Kriteria :");

        t_namaKriteria.setBackground(new java.awt.Color(255, 255, 255));
        t_namaKriteria.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_namaKriteria.setForeground(new java.awt.Color(0, 0, 0));
        t_namaKriteria.setCaretColor(new java.awt.Color(51, 51, 255));
        t_namaKriteria.addActionListener(this::t_namaKriteriaActionPerformed);

        t_bobot.setBackground(new java.awt.Color(255, 255, 255));
        t_bobot.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_bobot.setForeground(new java.awt.Color(0, 0, 0));
        t_bobot.setCaretColor(new java.awt.Color(51, 51, 255));
        t_bobot.addActionListener(this::t_bobotActionPerformed);

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bobot :");

        t_kode.setBackground(new java.awt.Color(255, 255, 255));
        t_kode.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        t_kode.setForeground(new java.awt.Color(0, 0, 0));
        t_kode.setCaretColor(new java.awt.Color(51, 51, 255));
        t_kode.addActionListener(this::t_kodeActionPerformed);

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Kriteria:");

        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jenis Kriteria :");

        combo_jenisKriteria.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        combo_jenisKriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Kriteria --", "Benefit", "Cost" }));
        combo_jenisKriteria.setBorder(null);
        combo_jenisKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_update.setBackground(new java.awt.Color(41, 54, 129));
        btn_update.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(this::btn_updateActionPerformed);

        btn_hapus.setBackground(new java.awt.Color(41, 54, 129));
        btn_hapus.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 13)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaKriteria)
                    .addComponent(t_kode)
                    .addComponent(combo_jenisKriteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_bobot)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_jenisKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_bobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahKaryawanLayout = new javax.swing.GroupLayout(tambahKaryawan);
        tambahKaryawan.setLayout(tambahKaryawanLayout);
        tambahKaryawanLayout.setHorizontalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahKaryawanLayout.setVerticalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(tambahKaryawan, "card2");

        jPanel1.add(mainPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
////        String kode = t_kode.getText();
////        String nama = t_namaKriteria.getText();
////        String jk = (String) combo_jenisKriteria.getSelectedItem();
////        String bobot = t_bobot.getText();
////
////        if(kode.isEmpty() || nama.isEmpty() || bobot.isEmpty()){
////            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
////            return;
////        }
////        try {
////            String sql = "INSERT INTO kriteria (id, nama_kriteria, jenis_kriteria, bobot) VALUES (?,?,?,?)";
////            PreparedStatement st = conn.prepareStatement(sql);
////            st.setString(1, kode);
////            st.setString(2, nama);
////            st.setString(3, jk);
////            st.setString(4, bobot);
////
////            int rowInserted = st.executeUpdate();
////            if (rowInserted > 0){
////                JOptionPane.showMessageDialog(this, "Data berhasil di input!");
//////                resetForm();
//////                getData();
////            }
////            st.close();
////        } catch (Exception e) {
////            logger.log(Level.SEVERE, "Error fetching Karyawan data", e);
////        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(report);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void t_bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bobotActionPerformed

    private void t_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
//        int selectedRow = tabel_kriteria.getSelectedRow();
//        if (selectedRow == -1) {
//            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di perbarui!", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        
//        String kode = t_kode.getText().trim();
//        String nama = t_namaKriteria.getText().trim();
//        String jk = (String) combo_jenisKriteria.getSelectedItem();
//        String bobot = t_bobot.getText().trim();
//        
//
//        if (kode.isEmpty() || nama.isEmpty() || jk == null || jk.isEmpty() || bobot.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        String sql = "UPDATE kriteria SET nama_kriteria=?, jenis_kriteria=?, bobot=? WHERE id=?";
//        try (PreparedStatement st = conn.prepareStatement(sql)) {
//            st.setString(1, nama);
//            st.setString(2, jk);
//            st.setDouble(3, Double.parseDouble(bobot));   // bobot = double, bukan String
//            st.setString(4, kode);                        // kode = id (varchar), dipakai di WHERE
//
//            int rowUpdated = st.executeUpdate();
//            if (rowUpdated > 0) {
//                JOptionPane.showMessageDialog(this, "Data berhasil di perbarui!");
//                resetForm();
//                nonAktifButton();
//                aktifButton();
//                getData();
//            } else {
//                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau tidak ada perubahan.", "Info", JOptionPane.WARNING_MESSAGE);
//            }
//        } catch (Exception e) {
//            logger.log(Level.SEVERE, "Error updating karyawan data", e);
//            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
//        }

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(report);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
//        int selectedRow = tabel_kriteria.getSelectedRow();
//        if(selectedRow == -1) {
//            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di hapus!", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        
//        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
//        if (confirm == JOptionPane.YES_OPTION) {
//            String id = tabel_kriteria.getValueAt(selectedRow, 0).toString();
//            
//            try {
//                String sql = "DELETE FROM kriteria WHERE id=?";
//                PreparedStatement st = conn.prepareStatement(sql);
//                st.setString(1, id);
//                
//                int rowDelete = st.executeUpdate();
//                if (rowDelete > 0) {
//                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
//                    resetForm();
//                    getData();
//                    aktifButton();
//                    nonAktifButton();
//                }
//                
//                st.close();
//            } catch(Exception e) {
//                logger.log(Level.SEVERE, "Error fetching karyawan data", e);
//            }
//        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void t_namaKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaKriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaKriteriaActionPerformed

    private void ctk_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctk_karyawanMouseClicked
        try {
            String reportPath ="src/ireport/laporan_data_karyawan.jasper";
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal cetak: " + ex.getMessage());
        }
    }//GEN-LAST:event_ctk_karyawanMouseClicked

    private void ctk_kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctk_kriteriaMouseClicked
        try {
            String reportPath ="src/ireport/laporan_data_kriteria.jasper";
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal cetak: " + ex.getMessage());
        }
    }//GEN-LAST:event_ctk_kriteriaMouseClicked

    private void ctk_penilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctk_penilaianMouseClicked
        try {
            String reportPath ="src/ireport/laporan_data_penilaian.jasper";
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal cetak: " + ex.getMessage());
        }
    }//GEN-LAST:event_ctk_penilaianMouseClicked

    private void ctk_rankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctk_rankingMouseClicked
        try {
            String reportPath ="src/ireport/laporan_data_perangkingan.jasper";
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal cetak: " + ex.getMessage());
        }
    }//GEN-LAST:event_ctk_rankingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_jenisKriteria;
    private javax.swing.JLabel ctk_karyawan;
    private javax.swing.JLabel ctk_kriteria;
    private javax.swing.JLabel ctk_penilaian;
    private javax.swing.JLabel ctk_ranking;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel report;
    private javax.swing.JTextField t_bobot;
    private javax.swing.JTextField t_kode;
    private javax.swing.JTextField t_namaKriteria;
    private javax.swing.JPanel tambahKaryawan;
    // End of variables declaration//GEN-END:variables
    
//    private void resetForm() {
//        t_kode.setText("");
//        t_namaKriteria.setText("");
//        combo_jenisKriteria.setSelectedItem("0");
//        t_bobot.setText("");
//    }
//    
//    private void nonAktifButton() {
//        btn_simpan.setEnabled(true);
//        btn_update.setEnabled(false);
//        btn_hapus.setEnabled(false);
//    }
//
//    private void aktifButton() {
//        btn_tambah.setEnabled(true);
//        btn_batal.setEnabled(true);
//    }


}
